export QT_QPA_PLATFORMTHEME=qt5ct
export BEMENU_OPTS="
                --fn 'JetBrainsMono Nerd Font Mono 32'\
                --tb '#6272a4'\
                --tf '#f8f8f2'\
                --fb '#282a36'\
                --ff '#f8f8f2'\
                --nb '#282a36'\
                --nf '#6272a4'\
                --hb '#44475a'\
                --hf '#50fa7b'\
                --sb '#44475a'\
                --sf '#50fa7b'\
                --scb '#282a36'\
                --scf '#ff79c6'\
                --bdr '#bd93f9'\
                -l 10\
                -c\
                -W 0.25\
                -p 'run'\
                -i\
                -B 4"
