#!/usr/bin/env bash
# lazy load nvm
if [[ -e ~/.nvm ]]
then 
    NODE_GLOBALS=(node nvm yarn)

    _load_nvm() {
	source /usr/share/nvm/init-nvm.sh # Require nvm to be installed via AUR
    }

    for cmd in "${NODE_GLOBALS[@]}"; do
	eval "function ${cmd}(){ unset -f ${NODE_GLOBALS[*]} 2> /dev/null; echo 'loading nvm'; _load_nvm; unset -f _load_nvm; ${cmd} \$@; }"
    done

    unset cmd NODE_GLOBALS
fi

# lazy load pyenv
if [[ -e ~/.pyenv ]]
then 
    PYENV_GLOBALS=(pyenv python pip)

    _load_pyenv() {
	source ~/.local/bin/lazy-pyenv
    }

    for cmd in "${PYENV_GLOBALS[@]}"; do
	eval "function ${cmd}(){ unset -f ${PYENV_GLOBALS[*]} 2> /dev/null; echo 'loading pyenv'; _load_pyenv; unset -f _load_pyenv; ${cmd} \$@; }"
    done

    unset cmd pyenv_GLOBALS
fi

alias pgadmin="pyenv activate pgadmin && pgadmin4"
          
# Helpful functions / Aliases
alias gitrmbranches="git branch --list| grep -v \* | xargs git branch -D"
alias pipunall="pip freeze | grep -v '^-e' | xargs pip uninstall -y"


# Better ls
alias ls="exa --icons --group-directories-first"
alias l="ls --git-ignore"
alias la="ls -a"
alias ll="ls -l --git --git-ignore"
alias lla="ls -l -a --git"

# Better cat
alias cat="bat"
export MANROFFOPT="-c" 
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Quick Emacs in Terminal
alias e="emacsclient -nw"

# Better grep
alias grep="rg"

# Ranger follow
alias lr=". ranger"

# Kitty SSH
alias s="kitten ssh"

alias updategrub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

update () {
    sudo test
    (cd ~/dotfiles && unstowall && git pull && stowall)
    curl "https://archlinux.org/mirrorlist/?country=CA&protocol=http&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on" > /tmp/mirrorlist
    sed -i 's/#//' /tmp/mirrorlist
    sudo mv /tmp/mirrorlist /etc/pacman.d/
    yay -Syyu --answerclean A --answerdiff N --removemake --noconfirm
    if command -v pyenv &> /dev/null; then
	pyenv update
    fi
    if command -v rustup &> /dev/null; then
        rustup update
    fi
}

tzupdate () {
    timedatectl set-timezone $(curl https://ipapi.co/timezone)
}

# Git stuff
gitc () {
    git add .
    git commit -m $1
    git push
}

alias gits="(git fetch &>/dev/null &) && git status"
alias gitl="git log --compact-summary"

configc () {
    config commit -am $1
    config push
}

export EDITOR="emacs -nw"
export GPG_TTY=$TTY

# Path Edits
export PATH="$HOME/.yarn/bin:$PATH"

# Set Terminal to English
export LANG=en_US.UTF-8
