#+TITLE: GNU Emacs Config
#+AUTHOR: Martin Chaperot
#+PROPERTY: header-args :tangle init.el
#+STARTUP: overview

* Usage
I use evil mode and evil mode collections. This means that vim like bindings apply almost everywhere. 
Other than that, i've set some custom bindings for myself. Here they are below. I also have which-key installed.
| Keybinding | Map      | Description                     |
|------------+----------+---------------------------------|
| SPC i      | org-mode | Edit a latex fragment (preview) |
| C-o        |          | Search for a file               |
| SPC RET    |          | Go to dashboard                 |
| C-e        |          | Toggle NeoTree                  |
| C-i        |          | imenu                           |
|------------+----------+---------------------------------|
| C-p        |          | Projectile Find File            |
| C-S-o      |          | Projectile Switch Project       |
| C-S-f      |          | Projectile Find Text            |
|------------+----------+---------------------------------|
| SPC b l    |          | List buffers                    |
| SPC b s    |          | Switch to buffer                |
| SPC b j    |          | Next buffer                     |
| SPC b k    |          | Previous buffer                 |
| SPC b h    |          | Kill current buffer             |

All custom bindings are defined here: [[#general]]
I've also defined bindings to make certain interfaces more vim-like (i.e. ivy minibuffer) but those are defined in the corresponding use-package.
* Package Manager 
Configure the package manager and package manager sources. We also want to use ~use-package~.

#+begin_src emacs-lisp
;; Setup Package Manager
(require 'package)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))

;; Initialize use-package
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

;; Add diminish
(use-package diminish)
#+end_src

* Keyboard
** EVIL Mode
#+begin_src emacs-lisp
(use-package evil
  :diminish
  :custom
  (evil-undo-system 'undo-redo)
  (evil-want-C-d-scroll t)
  (evil-want-C-u-scroll t)
  (evil-search-module 'swiper)
  (evil-auto-indent nil)
  (evil-want-keybinding nil)
  :config
  (evil-mode 1))
#+end_src
*** EVIL Collection
Additional keybindings to make evil work better
#+begin_src emacs-lisp
(use-package evil-collection 
  :diminish evil-collection-unimpaired-mode
  :after evil
  :config
  (evil-collection-init))
#+end_src
** General 
:PROPERTIES:
:CUSTOM_ID: general
:END:
#+begin_src emacs-lisp
(use-package general
  :after evil
  :config
  ; Better vim motions
  (general-define-key :states '(normal visual) "C-u" (general-simulate-key ('evil-scroll-up "z z")))
  (general-define-key :states '(normal visual) "C-d" (general-simulate-key ('evil-scroll-down "z z")))
  ; Prefixes
  (general-create-definer leader
    :states '(normal visual)
    :prefix "SPC")
  ; Bindings
  (leader org-mode-map "i" 'org-edit-latex-fragment)
  (general-define-key :states 'normal "C-o" 'find-file)
  (leader :states 'normal "RET" 'dashboard-open)
  (general-define-key :states 'normal "C-e" 'neotree-toggle)
  (general-define-key :states 'normal "C-i" 'lsp-ui-imenu)
  ; Projectile
  (general-define-key :states 'normal "C-p" 'projectile-find-file)
  (general-define-key :states 'normal "C-S-o" 'projectile-switch-project)
  (general-define-key :states 'normal "C-S-f" 'projectile-ripgrep)
  ; Buffer management
  (leader "b l" 'ibuffer)
  (leader "b i" 'switch-to-buffer)
  (leader "b j" 'next-buffer)
  (leader "b k" 'previous-buffer)
  (leader "b h" 'kill-current-buffer)
)
#+end_src
** Escape Binding
Makes escape quit whatever your doing just like in Vim
#+begin_src emacs-lisp
(global-set-key [escape] 'keyboard-escape-quit)
#+end_src

** Which Key
#+begin_src emacs-lisp
(use-package which-key
  :config
  (which-key-mode)
  (which-key-add-key-based-replacements "SPC b" "Buffer Management")
)
#+end_src
* UI Tweaks
** Language
#+begin_src emacs-lisp
(set-locale-environment "en_US.UTF-8")
(set-language-environment "English")
(setenv "LANG" "en_US.UTF-8")
#+end_src
** Theme
As always, I use the dracula theme
#+begin_src emacs-lisp
(use-package dracula-theme
  :config
  (load-theme 'dracula t)
)
#+end_src
** Modeline
[[https://github.com/seagle0128/doom-modeline?tab=readme-ov-file#screenshots][Doom Modeline]]
#+begin_src emacs-lisp
(use-package doom-modeline
  :init
  (doom-modeline-mode 1)
  :custom
  (doom-modeline-height 25)
  (doom-modeline-hud t)
  (doom-modeline-modal-modern-icon nil)
)
#+end_src
** Font
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(font . "JetBrainsMono Nerd Font-11"))
(set-face-attribute 'default nil :font "JetBrainsMono Nerd Font-11")
#+end_src
*** Ligatures
#+begin_src emacs-lisp
(use-package ligature
  :config
  (ligature-set-ligatures 't '("www"))
  ;; Enable traditional ligature support in eww-mode, if the
  ;; `variable-pitch' face supports it
  (ligature-set-ligatures 'eww-mode '("ff" "fi" "ffi"))
  ;; Enable all Cascadia Code ligatures in programming modes
  (ligature-set-ligatures 'prog-mode '("|||>" "<|||" "<==>" "<!--" "####" "~~>" "***" "||=" "||>"
                                       ":::" "::=" "=:=" "===" "==>" "=!=" "=>>" "=<<" "=/=" "!=="
                                       "!!." ">=>" ">>=" ">>>" ">>-" ">->" "->>" "-->" "---" "-<<"
                                       "<~~" "<~>" "<*>" "<||" "<|>" "<$>" "<==" "<=>" "<=<" "<->"
                                       "<--" "<-<" "<<=" "<<-" "<<<" "<+>" "</>" "###" "#_(" "..<"
                                       "..." "+++" "/==" "///" "_|_" "www" "&&" "^=" "~~" "~@" "~="
                                       "~>" "~-" "**" "*>" "*/" "||" "|}" "|]" "|=" "|>" "|-" "{|"
                                       "[|" "]#" "::" ":=" ":>" ":<" "$>" "==" "=>" "!=" "!!" ">:"
                                       ">=" ">>" ">-" "-~" "-|" "->" "--" "-<" "<~" "<*" "<|" "<:"
                                       "<$" "<=" "<>" "<-" "<<" "<+" "</" "#{" "#[" "#:" "#=" "#!"
                                       "##" "#(" "#?" "#_" "%%" ".=" ".-" ".." ".?" "+>" "++" "?:"
                                       "?=" "?." "??" ";;" "/*" "/=" "/>" "//" "__" "~~" "(*" "*)"
                                       "\\\\" "://"))
  (global-ligature-mode 't)
)
#+end_src
** Icons
*** [[https://github.com/rainstormstudio/nerd-icons.el][Nerd Fonts for Emacs]]
#+begin_src emacs-lisp
(use-package nerd-icons
  :custom 
  (nerd-icons-font-family "JetBrainsMono Nerd Font Mono")
 )
#+end_src
*** All the icons
#+begin_src emacs-lisp
(use-package all-the-icons)

(use-package all-the-icons-dired
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))
#+end_src

** Builtin UI Tweaks
#+begin_src emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)

(menu-bar-mode -1)

;; Line numbers
(column-number-mode)
(setq-default display-line-numbers-type 'relative)
(global-display-line-numbers-mode t)

;; Disable dialogs/popup windows'
(setq use-file-dialog nil)   ;; No file dialog
(setq use-dialog-box nil)    ;; No dialog box
(setq pop-up-windows nil)    ;; No popup windows

;; remove line wrap
(setq-default truncate-lines t)
;(toggle-truncate-lines 1)
#+end_src

** Transparency 
#+begin_src emacs-lisp
(set-frame-parameter nil 'alpha-background 90)

(add-to-list 'default-frame-alist '(alpha-background . 90))
#+end_src
** Other Tweaks
*** Rainbow Delimiters
Makes ~(~, ~[~, and ~{~ rainbow!
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

*** Rainbow Mode
Displays the color for any hex (i.e. #0000FF)
#+begin_src emacs-lisp
(use-package rainbow-mode
  :diminish
  :hook org-mode prog-mode)
#+end_src
*** Diminish ElDoc
#+begin_src emacs-lisp
(diminish 'eldoc-mode)
#+end_src

* Misc Packages
** Projectile
[[https://github.com/bbatsov/projectile][Projectile Github]]
#+begin_src emacs-lisp
(use-package projectile
  :diminish
  :config
  (projectile-mode 1))
#+end_src
*** Ripgrep support
#+begin_src emacs-lisp
(use-package ripgrep)
#+end_src
** Dashboard
[[https://github.com/emacs-dashboard/emacs-dashboard][Emacs Dashboard]]
#+begin_src emacs-lisp
(use-package dashboard
  :requires (nerd-icons projectile)
  :custom
  (dashboard-banner-logo-title "Hello Martin. Welcome to Emacs")
  (dashboard-startup-banner "~/.config/emacs/logo.webp")
  (dashboard-image-banner-max-height 250)
  (dashboard-center-content t)
  (dashboard-display-icons-p t)
  (dashboard-icon-type 'nerd-icons) 
  (dashboard-set-heading-icons t)
  (dashboard-set-file-icons t)
  (dashboard-projects-backend 'projectile)
  (dashboard-items '((projects . 10)
                     (recents  . 10)))
  :config
  (dashboard-setup-startup-hook))
#+end_src
Auto open dashboard
#+begin_src emacs-lisp
(setq initial-buffer-choice (lambda () (get-buffer-create dashboard-buffer-name)))
#+end_src
** Org Mode
#+begin_src emacs-lisp
(use-package org
  :diminish org-indent-mode
  :custom
  (org-hide-emphasis-markers t)
  (org-startup-indented t)
  (org-startup-with-latex-preview t)
  (org-startup-with-inline-images t)
  (org-image-actual-width '(0.5))
  (org-edit-src-content-indentation 0)
  (org-hide-leading-stars t)
)
#+end_src
*** Org Superstar
~org-superstar~ handles the nice rendering of bullets in headers and lists
#+begin_src emacs-lisp 
(use-package org-superstar
  :hook (org-mode . (lambda () (org-superstar-mode 1)))
  :config
  (setq org-superstar-leading-bullet "  ")
  (setq org-superstar-special-todo-items t))
#+end_src

*** Latex Formating
#+begin_src emacs-lisp
(setq org-format-latex-options 
  '(:foreground default 
    :background default 
    :scale 3
    :html-foreground "Black" 
    :html-background "Transparent" 
    :html-scale 1.0 
    :matchers ("begin" "$1" "$" "$$" "\\(" "\\[")))
(add-hook 'org-mode-hook
  (lambda ()
      (add-hook 'after-save-hook 'org-latex-preview nil 'make-local)))
#+end_src
*** Auto image rendering
#+begin_src emacs-lisp
(add-hook 'org-mode-hook
  (lambda ()
      (add-hook 'after-save-hook (lambda () (org-display-inline-images)))))
#+end_src
*** Auto Tangleing
Automatically tangles my org files
#+begin_src emacs-lisp
(add-hook 'org-mode-hook
    (lambda ()
        (add-hook 'after-save-hook #'org-babel-tangle
                nil 'make-it-local)))
#+end_src
** NeoTree
#+begin_src emacs-lisp
(use-package neotree
  :custom
  (neo-theme 'icons 'arrow)
)
#+end_src
* Language Support
** Tree Sitter (Syntax Highlighting)
*** Ensure treesitter
#+begin_src emacs-lisp
(require 'treesit)
(customize-set-variable 'treesit-font-lock-level 4)
#+end_src
*** Enable modes
#+begin_src emacs-lisp
(setq major-mode-remap-alist
 '((sh-mode . bash-ts-mode)
   (js-mode . js-ts-mode)
   (js-json-mode . json-ts-mode)
   (css-mode . css-ts-mode)
   (python-mode . python-ts-mode)
  )
)
#+end_src
** Markdown
[[https://jblevins.org/projects/markdown-mode][markdown-mode documentation]] 
#+begin_src emacs-lisp
(use-package markdown-mode)
#+end_src
** Web
#+begin_src emacs-lisp
(use-package web-mode
  :hook (
    (html-mode . web-mode)
    (mhtml-mode . web-mode)
  )
)
#+end_src
** LSP Mode
#+begin_src emacs-lisp
(use-package lsp-mode
  :hook (
    (css-ts-mode . lsp)
  )
  :commands lsp
)
(use-package lsp-ui)
#+end_src
** Python 
*** Pyright
#+begin_src emacs-lisp
(use-package lsp-pyright
  :hook (python-ts-mode . lsp)
  :init
  (setq lsp-pyright-multi-root nil)
)
#+end_src
** Java
LSP Java
#+begin_src emacs-lisp
(use-package lsp-java
  :hook (java-ts-mode . lsp)
)
#+end_src

* Quality of Life
** Ivy/Swiper
Handles the better autocompletion/search functionality in the minibuffer
#+begin_src emacs-lisp
(use-package ivy
:diminish
:bind (:map ivy-minibuffer-map
        ("C-l" . ivy-alt-done)
        ("TAB" . ivy-alt-done)
        ("C-j" . ivy-next-line)
        ("C-k" . ivy-previous-line))
:config
(setq ivy-switch-buffer-map nil) ; Remove default kill buffer binding
(ivy-mode 1))

(use-package swiper)
#+end_src
** Move Backup Files
#+begin_src emacs-lisp
(setq backup-directory-alist '(("." . "~/.config/emacs/backup"))
      backup-by-copying      t  ; Don't de-link hard links
      version-control        t  ; Use version numbers on backups
      delete-old-versions    t  ; Automatically delete excess backups:
      kept-new-versions      20 ; how many of the newest versions to keep
      kept-old-versions      2) ; and how many of the old
#+end_src
** Move Custom File
#+begin_src emacs-lisp
(setq custom-file "~/.config/emacs/emacs-custom.el")
(load custom-file)
#+end_src

** Enable Folding 
#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'hs-minor-mode)
#+end_src
** Auto Revert
#+begin_src emacs-lisp
(global-auto-revert-mode)
#+end_src
** Flycheck
Modern on-the-fly syntax checking extension. [[https://github.com/flycheck/flycheck][Github]]
#+begin_src emacs-lisp
(use-package flycheck
  :config
  (flycheck-mode)
)
#+end_src

** Company Mode
A text completion framework
#+begin_src emacs-lisp
(use-package company
  :config
  (company-mode)
)
#+end_src
