name = "system-control"
name_pretty = "System Control"
icon = "settings"
fixed_order = true

# Monitor stuff
[[entries]]
hosts = [ "martinpc" ]
text = "Set 1440p"
actions = { "set" = """hyprctl eval 'hl.monitor({ output = "desc:LG Electronics LG HDR 4K 0x00048B3D", mode = "2560x1440@60", position = "0x0", scale = 1 })'""" }
icon = "monitor-symbolic"

[[entries]]
hosts = [ "martinfw" ]
text = "Enable mirroring"
actions = { "enable" = """hyprctl eval 'hl.monitor({ output = "", mode = "preferred", position = "auto-right", scale = 1, mirror = "eDP-1" })'""" }
icon = "monitor-symbolic"

[[entries]]
hosts = [ "martinfw" ]
text = "Disable mirroring"
actions = { "enable" = """hyprctl eval 'hl.monitor({ output = "", mode = "preferred", position = "auto-right", scale = 1 })'""" }
icon = "monitor-symbolic"

# Power management
[[entries]]
hosts = [ "martinfw" ]
text = "Power Management"
submenu = "power-management"
icon = "power-symbolic"

# System
[[entries]]
text = "Reboot"
keywords = ["reboot", "restart"]
actions = { "reboot" = "systemctl reboot" }
icon = "system-reboot-symbolic"

[[entries]]
text = "Power Off"
keywords = ["power", "off", "shutdown", "poweroff"]
actions = { "poweroff" = "systemctl poweroff" }
icon = "system-shutdown-symbolic"

[[entries]]
text = "Logout"
keywords = ["logout", "exit", "quit"]
actions = { "logout" = "loginctl terminate-user $USER" }
icon = "system-log-out-symbolic"

# Misc
[[entries]]
text = "Color Picker"
keywords = ["color", "picker", "hypr"]
actions = { "pick" = "wl-copy $(hyprpicker)" }
icon = "color-picker"

