--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/martin/dotfiles/dot-local/share/backgrounds/wallpaper.png"

-- Special
background="#060410"
foreground="#dec5e2"
cursor="#dec5e2"

-- Colors
color0="#060410"
color1="#553296"
color2="#524BB4"
color3="#614AA2"
color4="#9E589E"
color5="#B659B5"
color6="#7A84EA"
color7="#dec5e2"
color8="#9b899e"
color9="#553296"
color10="#524BB4"
color11="#614AA2"
color12="#9E589E"
color13="#B659B5"
color14="#7A84EA"
color15="#dec5e2"
