# Shell variables
# Generated by 'wal'
wallpaper='/home/martin/dotfiles/dot-local/share/backgrounds/wallpaper.png'

# Special
background='#060410'
foreground='#dec5e2'
cursor='#dec5e2'

# Colors
color0='#060410'
color1='#553296'
color2='#524BB4'
color3='#614AA2'
color4='#9E589E'
color5='#B659B5'
color6='#7A84EA'
color7='#dec5e2'
color8='#9b899e'
color9='#553296'
color10='#524BB4'
color11='#614AA2'
color12='#9E589E'
color13='#B659B5'
color14='#7A84EA'
color15='#dec5e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
