arch = {
    packages = [
        # core linux
        "base",
        "base-devel",
        "limine",
        "limine-mkinitcpio-hook",
        "linux-firmware",
        "pacman-contrib",
        "efibootmgr",

        # docs
        "man-db",
        "man-pages",
        "tldr",

        # required shell stuff
        "yay",
        "metapac",
        "git",

        # connectivity
        "openssh",
        "iwd",

        # low level control (platform independent)
        "fwupd",
        "dmidecode",
    ]
}
