# Arch desktop foundation
arch = {
    packages = [
        # core Linux
        {
            name = "base",
            hooks = {
                after_sync = [
                    "sudo",
                    "systemctl",
                    "enable",
                    "systemd-networkd.service",
                    "systemd-resolved.service",
                    "systemd-timesyncd.service",
                ]
            }
        },
        "base-devel",
        "linux-firmware",
        "pacman-contrib",

        # CachyOS repositories
        "cachyos-keyring",
        "cachyos-mirrorlist",
        "cachyos-v3-mirrorlist",
        "cachyos-v4-mirrorlist",

        # Btrfs and boot
        "limine",
        "limine-mkinitcpio-hook",
        "efibootmgr",
        "btrfs-progs",
        {
            name = "snapper",
            hooks = {
                after_sync = [
                    "sudo",
                    "systemctl",
                    "enable",
                    "snapper-cleanup.timer",
                    "snapper-timeline.timer",
                ]
            }
        },
        "compsize",
        "snap-pac",
        "limine-snapper-sync",
        "plymouth",

        # docs
        "man-db",
        "man-pages",
        "tldr",

        # package management
        "paru",
        "metapac",
        "git",
        "git-lfs",
        "reflector",

        # connectivity and Wi-Fi
        {
            name = "openssh",
            hooks = {
                after_sync = [
                    "sudo",
                    "systemctl",
                    "enable",
                    "sshd",
                ]
            }
        },
        "iw",
        {
            name = "iwd",
            hooks = {
                after_sync = [
                    "sudo",
                    "systemctl",
                    "enable",
                    "iwd.service",
                ]
            }
        },
        "wireless-regdb",

        # low-level control
        "fwupd",
        "dmidecode",
    ]
}
