# Arch desktop foundation
arch = {
    packages = [
        # core Linux
        "base",
        "base-devel",
        "linux-firmware",
        "pacman-contrib",

        # CachyOS repositories
        "cachyos-keyring",
        "cachyos-mirrorlist",
        "cachyos-v3-mirrorlist",
        "cachyos-v4-mirrorlist",

        # Btrfs and boot
        "limine",
        "limine-mkinitcpio-hook",
        "efibootmgr",
        "btrfs-progs",
        "snapper",
        "compsize",
        "snap-pac",
        "limine-snapper-sync",
        "plymouth",

        # docs
        "man-db",
        "man-pages",
        "tldr",

        # package management
        "yay",
        "metapac",
        "git",
        "git-lfs",
        "reflector",

        # connectivity and Wi-Fi
        "openssh",
        "iw",
        "iwd",
        "wireless-regdb",

        # low-level control
        "fwupd",
        "dmidecode",
    ]
}
