arch = {
    packages = [
        # cachy things
        "cachyos-keyring",
        "cachyos-mirrorlist",
        "cachyos-v3-mirrorlist",
        "cachyos-v4-mirrorlist",

        # pipewire
        "pipewire",
        "pipewire-alsa",
        "pipewire-jack",
        "pipewire-pulse",
        "gst-plugin-pipewire",
        "lib32-pipewire",
        "alsa-utils",
        "alsa-tools",
        "plymouth",

        # essentials
        "ghostty",
        "nautilus",

        # daily drivers
        "zen-browser-bin",
        "slack-desktop",
        "spotify-launcher",

        # misc
        "obsidian",
        "helium-browser-bin",
        "vesktop-bin",
        "kicad",
        "kicad-library",

        # misc utilities
        "qalculate-gtk",
        "gimp",
        "mpv",
        "xournalpp",
        "papers",
        "typst",
        "postgresql",
        "jupyterlab",
        "patchelf",
        "syncthing",
        "kanata-bin",
        "onlyoffice-bin",
        "ttf-aptos",

        # virtmanger
        "qemu-full",
        "dnsmasq",
        "libvirt",
        "virt-manager",
    ]
}
