arch = {
    packages = [
        # audio
        "pipewire",
        "pipewire-alsa",
        "pipewire-jack",
        "pipewire-pulse",
        "gst-plugin-pipewire",
        "lib32-pipewire",
        "alsa-utils",
        "alsa-tools",

        # services
        {
            name = "kanata-bin",
            hooks = {
                after_sync = [
                    "systemctl",
                    "--user",
                    "enable",
                    "kanata.service",
                ],
            },
        },
        {
            name = "syncthing",
            hooks = {
                after_sync = [
                    "sudo",
                    "systemctl",
                    "enable",
                    "syncthing@martin",
                ]
            }
        },
        "localsend",
        {
            name = "voxtype-bin",
            hooks = {
                after_sync = [
                    "systemctl",
                    "--user",
                    "enable",
                    "voxtype.service",
                ],
            },
        },
        "wtype", # optional for voxtype

        # hw utils
        {
            name = "bluez-utils",
            hooks = {
                after_sync = [
                    "sudo",
                    "systemctl",
                    "enable",
                    "bluetooth.service",
                ]
            }
        },
        "dualsensectl-git",
        "brightnessctl",
        "ddcutil",

        # secrets store
        "kwallet",
        "kwallet-pam",
        "kwalletmanager",

        # screenshots
        "grim",
        "slurp",
        "swappy",

        # basic utils
        "wl-clipboard",
        "playerctl",
    ]
}
