arch = {
    packages = [
        # neovim
        "neovim",
        "lazygit",
        "tree-sitter-cli",

        # misc dev apps
        "t3code-bin",
        "voxtype-bin",
        "ollama",
        "browser-use-cli",
        "openai-codex",
        "python-openai-whisper",

        # languages
        "clang",
        "go",
        "typescript",

        # tooling
        "cmake",
        "gdb",
        "valgrind",
        "just",
        "pnpm",
        "platformio-core",
        "platformio-core-udev",
        "hugo",
        "uv"
    ]
}
