arch = {
    packages = [
        # neovim
        "neovim",
        "lazygit",
        "tree-sitter-cli",

        # tmux
        "tmux",
        "tmux-plugin-manager",

        # misc dev apps
        "codex-desktop", # managed/installed with make
        "openai-codex",
        "t3code-bin",
        "opencode",

        # clis
        {
            name = "ollama",
            hooks = {
                after_sync = [
                    "sudo",
                    "systemctl",
                    "enable",
                    "ollama.service",
                ]
            }
        },
        "python-openai-whisper",
        "github-cli",
        "direnv",

        # languages
        "clang",
        "go",
        "typescript",
        "rustup",
        "typst",

        # tooling
        "cmake",
        "gdb",
        "valgrind",
        "just",
        "pnpm",
        "platformio-core",
        "platformio-core-udev",
        "hugo",
        "uv",
        "postgresql",

        # podman
        {
            name = "podman",
            hooks = {
                after_sync = [
                    "systemctl",
                    "--user",
                    "enable",
                    "podman.socket",
                ],
            },
        },
        "docker-compose",
    ]
}
