arch = {
    packages = [
        # neovim
        "neovim",
        "lazygit",
        "tree-sitter-cli",

        # misc dev apps
        "codex-desktop", # managed/installed with make
        "t3code-bin",
        "freecad",

        # clis
        "voxtype-bin",
        "ollama",
        "python-openai-whisper",

        # languages
        "clang",
        "go",
        "typescript",
        "rustup",

        # tooling
        "cmake",
        "gdb",
        "valgrind",
        "just",
        "pnpm",
        "platformio-core",
        "platformio-core-udev",
        "hugo",
        "uv"
    ]
}
