arch = [
    # gaming
    "steam",
    "gamescope",
    "gamemode",
    "lib32-gamemode",
    "proton-ge-custom-bin",
    "protontricks",
    "mangohud",
    "libxnvctrl",

    # misc
    "obs-studio",
]
