arch = {
    packages = [
        # gaming
        "steam",
        "gamescope",
        "gamemode",
        "lib32-gamemode",
        "proton-ge-custom-bin",
        "proton-cachyos-slr",
        "protontricks",
        "mangohud",
        "libxnvctrl",

        # misc
        "lact",
    ]
}
