arch = {
    packages = [
        # kernel
        "linux",
        "linux-headers",

        # plymouth theme
        "plymouth-theme-framework-git",

        # amd
        "amd-ucode",
        "mesa",
        "lib32-mesa",
        "vulkan-radeon",
        "rocm-smi-lib",  # for btop gpu output

        # Better scheduler
        "scx-scheds",
        "scx-tools",

        # hardware control
        "acpi",
        "framework-system",
        "iw",
        "iwd",
        "power-profiles-daemon",
        "fprintd",
        "powertop",
        "wireless-regdb",
    ]
}
