arch = {
    packages = [
        # gaming
        "steam",
        "gamescope",
        "gamemode",
        "lib32-gamemode",
        "proton-ge-custom-bin",
        "proton-cachyos-slr",
        "protontricks",
        "mangohud",

        # miscellaneous gaming hardware utility
        {
            name = "lact",
            hooks = {
                after_sync = [
                    "sudo",
                    "systemctl",
                    "enable",
                    "lactd.service",
                ]
            }
        },
    ]
}
