arch = {
    packages = [
        # hypr-suite
        "hyprland",
        "hypridle",
        "hyprlock",
        "hyprpicker",
        "hyprsunset",
        "hyprpolkitagent",
        "aquamarine",
        "hyprcursor",
        "hyprgraphics",
        "hyprland-guiutils",
        "hyprlang",
        "hyprtoolkit",
        "hyprutils",
        "hyprwayland-scanner",
        "hyprwire",

        # session
        "uwsm",
        "app2unit",

        # input
        "fcitx5",

        # screensharing
        "xdg-desktop-portal-hyprland",
        "xdg-desktop-portal-gtk",

        # optional Hyprland dependencies
        "xorg-xwayland",
        "cpio",
        "wev",
    ]
}
