arch = {
    packages = [
        # hypr-suite
        "hyprland",
        {
            name = "hypridle",
            hooks = {
                after_sync = [
                    "systemctl",
                    "--user",
                    "enable",
                    "hypridle.service",
                ],
            },
        },
        "hyprlock",
        "hyprpicker",
        {
            name = "hyprsunset",
            hooks = {
                after_sync = [
                    "systemctl",
                    "--user",
                    "enable",
                    "hyprsunset.service",
                ],
            },
        },
        {
            name = "hyprpolkitagent",
            hooks = {
                after_sync = [
                    "systemctl",
                    "--user",
                    "enable",
                    "hyprpolkitagent.service",
                ],
            },
        },
        "aquamarine",
        "hyprcursor",
        "hyprgraphics",
        "hyprland-guiutils",
        "hyprlang",
        "hyprtoolkit",
        "hyprutils",
        "hyprwayland-scanner",
        "hyprwire",

        # session
        "uwsm",
        "app2unit",

        # input
        "fcitx5",

        # screensharing
        "xdg-desktop-portal-hyprland",
        "xdg-desktop-portal-gtk",

        # optional Hyprland dependencies
        "xorg-xwayland",
        "cpio",
        "wev",
    ]
}
