arch = [
    "perl-file-homedir",
    "perl-yaml-tiny",
    "texlive-basic",
    "texlive-binextra",
    "texlive-context",
    "texlive-fontsrecommended",
    "texlive-fontutils",
    "texlive-formatsextra",
    "texlive-latex",
    "texlive-latexextra",
    "texlive-latexrecommended",
    "texlive-luatex",
    "texlive-mathscience",
    "texlive-metapost",
    "texlive-pictures",
    "texlive-plaingeneric",
    "texlive-pstricks",
    "texlive-xetex",
]
