arch = {
    packages = [
        # shell + prompt
        "fish",
        "oh-my-posh-bin",

        # utils
        "vim",
        "fastfetch",
        "btop",
        "nvtop",
        "stress",
        "tree",
        "unzip",
        "zip",
        "wget",
        "rsync",
        "bind",       # dig, etc
        "stow",
        "jq",
        "7zip",
        "fd",
        "imagemagick",
        "chafa",
        "openbsd-netcat",
        "ripgrep",
        "eza",
        "bat",
        "fzf",
        "zoxide",
    ]
}
