#!/usr/bin/env bash

mag="\e[35m"
green="\e[32m"
reset="\e[m"

# System upgrade
sudo pacman -Syu

# Arch post-install requirements
sudo pacman -S --needed \
    base-devel \
    man-db man-pages texinfo \
    git github-cli openssh \
    zsh \
    stow


# Manpage setup
sudo mandb

# Configure user
chsh -s /bin/zsh
sudo usermod -aG video,input,wheel $USER

# Setup dotfiles
cd $HOME
printf "$mag""Authenticate gh with a new SSH Key (auth with web browser)""$reset""\n"
gh auth login # login with ssh
gh repo clone tinmarr/dotfiles
cd dotfiles
./stowall
cd $HOME

# Install utilities
printf "$mag""Installing Utilities""$reset""\n"
curl https://pyenv.run | bash
git clone https://github.com/alefpereira/pyenv-pyright.git ~/.pyenv/plugins/pyenv-pyright
git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd .. && rm -rf yay
git clone https://aur.archlinux.org/metapac-bin.git && cd metapac-bin && makepkg -si && cd .. && rm -rf metapac-bin

sudo test
yes | metapac sync

if [[ $(yay -Q ly) ]]; then
    sudo systemctl enable ly
    sudo systemctl disable getty@tty2.service
fi

if [[ $(yay -Q hyprland) ]]; then
    systemctl --user enable waybar.service hypridle.service hyprpaper.service hyprsunset.service
fi

printf "$mag""metapac was run for $HOST.$reset\n"
printf "If it was configured yet, metapac should be configured then rerun (services won't be automatic either).\n"

printf "$mag""The following tools (in installed) need to be configured manually:
    - nwg-look
    - qt6ct
    - zen-browser
    - GPG key""$reset""\n"

printf "$green""Setup Complete!""$reset""\n"
